USE `bus_service`;
DROP procedure IF EXISTS `GET_APPLICAITION_BY_ID`;

DELIMITER $$
USE `bus_service`$$
CREATE PROCEDURE `GET_APPLICAITION_BY_ID` (IN APPLICATION_ID VARCHAR(255))
BEGIN
SELECT * FROM PASS_APPLICATION_MASTER PAM WHERE PAM.APPLICATION_ID = APPLICATION_ID;
END$$

DELIMITER ;

