USE `bus_service`;
DROP procedure IF EXISTS `INS_PASS_APPLICATION`;

USE `bus_service`;
DROP procedure IF EXISTS `bus_service`.`INS_PASS_APPLICATION`;
;

DELIMITER $$
USE `bus_service`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INS_PASS_APPLICATION`(
 IN APPLICATION_ID INT ,
    in STUDENT_ID VARCHAR(255),
    in NAME VARCHAR(255),
    in APPLICATION_DATE DATE,
    in GENDER VARCHAR(25),
    in PASS_TYPE VARCHAR(100),
    in IS_RURAL BOOLEAN,
    in DISTRICT_PERMANANT VARCHAR(255),
    in BLOCK_PERMANANT VARCHAR(255),
    in CLUSTER_PERMANANT VARCHAR(255),
    in VILLAGE_PERMANANT VARCHAR(255),
    in DISTRICT_CURRENT VARCHAR(255),
    in STATUS VARCHAR(30),
    in BLOCK_CURRENT VARCHAR(255),
    in CLUSTER_CURRENT VARCHAR(255),
    in VILLAGE_CURRENT VARCHAR(255),
    in SECTION VARCHAR(50),
    in ROLL_NUMBER VARCHAR(50),
    in DATE_OF_BIRTH DATE,
    in CLASS VARCHAR(50),
    in CLASS_GROUP VARCHAR(50),
    in CATEGORY VARCHAR(50),
    in SCHOOL_NAME VARCHAR(255),
    in SCHOOL_ADDRESS VARCHAR(500),
    in ADDRESS_PERMANANT VARCHAR(500),
    in ADDRESS_CURRENT VARCHAR(500),
    in SAME_AS_PERMANANT BOOLEAN,
    in FROM_LOCATION VARCHAR(255),
    in TO_LOCATION VARCHAR(255),
    in ROUTE VARCHAR(255),
    in COUNTER_NAME VARCHAR(255),
    in STAGE INT,
    in ACADEMIC_YEAR VARCHAR(50),
    in TERM VARCHAR(50),
    in TERM_FROM DATE,
    in TERM_TO DATE,
    in NUMBER_OF_DAYS INT,
    in PASS_DURATION VARCHAR(50),
    in PASS_FROM DATE,
    in PASS_TO DATE,
    in IS_DEPOSIT BOOLEAN,
    in DEPOSIT_AMOUNT DECIMAL(10, 2),
    in PASS_AMOUNT DECIMAL(10, 2),
    in TOTAL_PASS_AMOUNT DECIMAL(10, 2),
    in ICARD_AMOUNT DECIMAL(10, 2),
    in PAYABLE_AMOUNT DECIMAL(10, 2),
    in MOBILE_NUMBER VARCHAR(15),
    in EMAIL VARCHAR(255),
    in PAYMENT_METHOD VARCHAR(50),
    in CREATED_DATETIME DATETIME,
    in CREATED_USER_ID VARCHAR(255),
    in UPDATED_DATETIME DATETIME,
    in UPDATED_USER_ID VARCHAR(255),
    in IS_ACTIVE BOOLEAN
)
BEGIN
INSERT INTO PASS_APPLICATION_MASTER (
        APPLICATION_ID, NAME, STUDENT_ID, APPLICATION_DATE, GENDER, PASS_TYPE, IS_RURAL, DISTRICT_PERMANANT,
        BLOCK_PERMANANT, CLUSTER_PERMANANT, VILLAGE_PERMANANT, DISTRICT_CURRENT, BLOCK_CURRENT, CLUSTER_CURRENT,
        VILLAGE_CURRENT, STATUS, SECTION, ROLL_NUMBER, DATE_OF_BIRTH, CLASS, CLASS_GROUP, CATEGORY, SCHOOL_NAME,
        SCHOOL_ADDRESS, ADDRESS_PERMANANT, ADDRESS_CURRENT, SAME_AS_PERMANANT, FROM_LOCATION, TO_LOCATION, ROUTE,
        COUNTER_NAME, STAGE, ACADEMIC_YEAR, TERM, TERM_FROM, TERM_TO, NUMBER_OF_DAYS, PASS_DURATION, PASS_FROM, PASS_TO,
        IS_DEPOSIT, DEPOSIT_AMOUNT, PASS_AMOUNT, TOTAL_PASS_AMOUNT, ICARD_AMOUNT, PAYABLE_AMOUNT, MOBILE_NUMBER, EMAIL,
        PAYMENT_METHOD, CREATED_DATETIME, CREATED_USER_ID, UPDATED_DATETIME, UPDATED_USER_ID, IS_ACTIVE
    ) VALUES (
        APPLICATION_ID, NAME, STUDENT_ID, APPLICATION_DATE, GENDER, PASS_TYPE, IS_RURAL, DISTRICT_PERMANANT,
        BLOCK_PERMANANT, CLUSTER_PERMANANT, VILLAGE_PERMANANT, DISTRICT_CURRENT, BLOCK_CURRENT, CLUSTER_CURRENT,
        VILLAGE_CURRENT, STATUS, SECTION, ROLL_NUMBER, DATE_OF_BIRTH, CLASS, CLASS_GROUP, CATEGORY, SCHOOL_NAME,
        SCHOOL_ADDRESS, ADDRESS_PERMANANT, ADDRESS_CURRENT, SAME_AS_PERMANANT, FROM_LOCATION, TO_LOCATION, ROUTE,
        COUNTER_NAME, STAGE, ACADEMIC_YEAR, TERM, TERM_FROM, TERM_TO, NUMBER_OF_DAYS, PASS_DURATION, PASS_FROM, PASS_TO,
        IS_DEPOSIT, DEPOSIT_AMOUNT, PASS_AMOUNT, TOTAL_PASS_AMOUNT, ICARD_AMOUNT, PAYABLE_AMOUNT, MOBILE_NUMBER, EMAIL,
        PAYMENT_METHOD, CURDATE(), CREATED_USER_ID, UPDATED_DATETIME, UPDATED_USER_ID, IS_ACTIVE 
    );
END$$

DELIMITER ;
;

