USE `bus_service`;
DROP procedure IF EXISTS `GET_APPLICAITION_BY_STD_ID`;

DELIMITER $$
USE `bus_service`$$
CREATE PROCEDURE `GET_APPLICAITION_BY_STD_ID` (IN STUDENT_ID VARCHAR(255))
BEGIN
SELECT * FROM PASS_APPLICATION_MASTER PAM WHERE PAM.STUDENT_ID = STUDENT_ID;
END$$

DELIMITER ;