DELIMITER //
CREATE PROCEDURE GET_STUDENT_MASTER(
	IN EMAIL VARCHAR(255)
)
BEGIN
		SELECT CT.STUDENT_ID,CT.NAME,CT.BIRTH_DATE,CT.EMAIL,CT.ROLE_ID,PASSWORD FROM (
        SELECT 
			SM.STUDENT_ID 'STUDENT_ID',
            UM.NAME 'NAME',
            UM.BIRTH_DATE 'BIRTH_DATE',
            UM.EMAIL 'EMAIL',
            UM.ROLE_ID 'ROLE_ID',
            UM.PASSWORD 'PASSWORD'
        
        FROM USER_MASTER UM INNER JOIN STUDENT_MASTER SM ON UM.EMAIL = SM.EMAIL WHERE UM.EMAIL = EMAIL and UM.EMAIL is not null) CT;
END;
DELIMETER;
