USE `bus_service`;
DROP procedure IF EXISTS `GET_ALL_APPLICATIONS`;

USE `bus_service`;
DROP procedure IF EXISTS `bus_service`.`GET_ALL_APPLICATIONS`;
;

DELIMITER $$
USE `bus_service`$$
CREATE PROCEDURE `GET_ALL_APPLICATIONS`()
BEGIN
	SELECT * FROM PASS_APPLICATION_MASTER PAM ORDER BY PAM.CREATED_DATETIME; 
END$$

DELIMITER ;
;
